### ISSUE TITLE
Buttons (boolean objects) displayed in a row

### ISSUE THREAD

**Issue by xan2622** [omnitrix9991/MeshVolumeModellerB3D#2]
Hi.

To save vertical space, would it be possible to place buttons in a row (instead of having several wide buttons)?

![several_buttons_in_one_row](https://user-images.githubusercontent.com/1732773/80208448-8835c980-8630-11ea-85f8-ac7dac7bbaec.png)

Thank you in advance.

**Comment by omnitrix9991** [comment]
Thanks for feedback, done in the latest commit
